notifications:
  email:
    on_success: never
    on_failure: change

os:
  - osx
  - linux

branches:
  only:
    - master
    - /^__release-.*/
    - linux

language: node_js
node_js:
  - "7"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:jblgf0/outros3-precise -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libsecret-1-dev gcc-4.8 g++-4.8 -y; fi
env:
  CXX=g++-4.8

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install -g npm@4.6.1
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

script:
  - npm run lint
  - npm run build:prod
  - npm run test:setup
  - npm test

after_success:
  - npm run publish

after_failure:
  - npm run test:review
